
// Hard-coded list of confirmed attendees who RSVP'd "Yes"
const attendees = [
  { first_name: "Penny", last_name: "Folloder" },
  { first_name: "Jeff", last_name: "Folloder" },
  { first_name: "Nate", last_name: "Smith" },
  { first_name: "Chris", last_name: "Cheng" },
  { first_name: "Joyce", last_name: "Wang" },
  { first_name: "Jay", last_name: "Marme" },
  { first_name: "Marlena", last_name: "Winkler" },
  { first_name: "Jackie", last_name: "Smith" },
  { first_name: "Adam", last_name: "Cicciarella" },
  { first_name: "Yatin", last_name: "Chawathe" },
  { first_name: "Isaac", last_name: "Titus" },
  { first_name: "Cora", last_name: "Palomares" },
  { first_name: "Dave", last_name: "Bogaty" },
  { first_name: "Jonathan", last_name: "Agudelo" },
  { first_name: "Viktoria", last_name: "Sodini" },
  { first_name: "Darrell", last_name: "Silver" },
  { first_name: "Scott", last_name: "Takishita" },
  { first_name: "Brendan", last_name: "Doms" },
  { first_name: "Anne", last_name: "Dunkley" },
  { first_name: "Allison", last_name: "Cheng" },
  { first_name: "Jordan", last_name: "Yelinek" },
  { first_name: "Nicole", last_name: "Schofield" },
  { first_name: "Michael", last_name: "Neeley" },
  { first_name: "Kent", last_name: "Schofield" },
  { first_name: "Cruz", last_name: "Takishita" },
  { first_name: "Alex", last_name: "Karpman" },
  { first_name: "Zac", last_name: "Scott" },
  { first_name: "Jaron", last_name: "Gandelman" },
  { first_name: "Josie", last_name: "Smith-Campbell" },
  { first_name: "Michael", last_name: "Keller" },
  { first_name: "Nundu", last_name: "Janakiram" },
  { first_name: "Nicole", last_name: "Wilke" },
  { first_name: "Leighton", last_name: "Wallace" },
  { first_name: "Victoria", last_name: "Smith-Campbell" },
  { first_name: "Lee", last_name: "Edwards" },
  { first_name: "Zach", last_name: "Hoover" },
  { first_name: "Michael", last_name: "Belkin" },
  { first_name: "Ryan", last_name: "Takishita" },
  { first_name: "Sandeep", last_name: "Bhadra" },
  { first_name: "Chris", last_name: "Lloyd" },
  { first_name: "Scott", last_name: "Harding" },
  { first_name: "Mark", last_name: "Hanish" },
  { first_name: "William", last_name: "Ho" },
  { first_name: "Melodie", last_name: "Shimomura" },
  { first_name: "Norma", last_name: "Neeley" },
  { first_name: "Mike", last_name: "Sodini" },
  { first_name: "Josh", last_name: "Lord" },
  { first_name: "Ernesto", last_name: "Tsuchiya" },
  { first_name: "Heather", last_name: "Heistand" },
  { first_name: "Maggie", last_name: "Cheng" },
  { first_name: "Ben", last_name: "Cheng" },
  { first_name: "Nell", last_name: "Triplett" },
  { first_name: "Brian", last_name: "Shih" },
  { first_name: "Kelly", last_name: "de Bartok" },
  { first_name: "Simon", last_name: "Fong" },
  { first_name: "Adam", last_name: "Cray" },
  { first_name: "Brandt", last_name: "Anderson" },
  { first_name: "Nick", last_name: "Cheng" },
  { first_name: "Teddy", last_name: "Winkler" },
  { first_name: "Lucas", last_name: "Paul" },
  { first_name: "Anne", last_name: "Schwab" },
  { first_name: "Zach", last_name: "Cheng" },
  { first_name: "Emma", last_name: "Palomares" },
  { first_name: "Reia", last_name: "Davidson" },
  { first_name: "Sean", last_name: "McBride" },
  { first_name: "Lorina", last_name: "Noveske" },
  { first_name: "Rajeev", last_name: "Behera" },
  { first_name: "Kristine", last_name: "Wise" },
  { first_name: "Matt", last_name: "Spooner" },
  { first_name: "Troy", last_name: "Heitzinger" },
  { first_name: "Michael", last_name: "Ducker" },
  { first_name: "Frank", last_name: "Cheng" },
  { first_name: "Chris", last_name: "Dzoba" },
  { first_name: "Gary", last_name: "Campbell" },
  { first_name: "Derek", last_name: "Jackson" },
  { first_name: "Lori", last_name: "Anderson" },
  { first_name: "David", last_name: "Wilkinson" },
  { first_name: "Matt", last_name: "Dolan" },
  { first_name: "KC", last_name: "Gleason" },
  { first_name: "Sherry", last_name: "Shimomura" },
  { first_name: "Jamila", last_name: "Janakiram" },
  { first_name: "Zach", last_name: "Brock" },
  { first_name: "Vinney", last_name: "Le" },
  { first_name: "Alex", last_name: "Winkler" },
  { first_name: "Ian", last_name: "Titus" },
  { first_name: "Matt", last_name: "Wise" },
  { first_name: "Ashley", last_name: "Hlebinsky" },
  { first_name: "Kathy", last_name: "Cheng" },
  { first_name: "Lindsay", last_name: "Gordon" },
  { first_name: "Max", last_name: "Winkler" },
  { first_name: "Chris", last_name: "Nishimura" },
  { first_name: "Lesley", last_name: "Cicciarella" },
  { first_name: "Julie", last_name: "Spooner" },
  { first_name: "Sam", last_name: "Shuler" },
  { first_name: "Morten", last_name: "Jacobsen" },
  { first_name: "Tim", last_name: "Bavaro" },
  { first_name: "Charitha", last_name: "Reddy" },
  { first_name: "Matt", last_name: "Colyer" },
  { first_name: "Sheena", last_name: "Palomares" },
  { first_name: "Steve", last_name: "Cary" },
  { first_name: "Alex", last_name: "Chen" },
  { first_name: "Andy", last_name: "Wheeler" },
  { first_name: "Russell", last_name: "Dunkley" },
  { first_name: "Stephen", last_name: "Foley" },
  { first_name: "Surbhi", last_name: "Sarna" },
  { first_name: "Ben", last_name: "Schwab" },
  { first_name: "Jackie", last_name: "Bavaro" },
  { first_name: "Tom", last_name: "Zambito" },
  { first_name: "Jigish", last_name: "Patel" },
  { first_name: "Eric", last_name: "Lukoff" },
];

export default function ConfirmedAttendees() {
  
  return (
    <div className="grid grid-cols-3 gap-x-3 gap-y-2 md:gap-x-4 md:gap-y-3 max-w-[700px] mx-auto">
      {attendees.map((guest, index) => (
        <div 
          key={index} 
          className="text-[#C2C2C2] text-xs md:text-sm font-bicyclette text-center uppercase"
        >
          {guest.first_name} {guest.last_name}
        </div>
      ))}
    </div>
  );
}
