
// Hard-coded list of confirmed attendees who RSVP'd "Yes"
const attendees = [
  { first_name: "Jonathan", last_name: "Agudelo" },
  { first_name: "Brandt", last_name: "Anderson" },
  { first_name: "Lori", last_name: "Anderson" },
  { first_name: "Tim", last_name: "Bavaro" },
  { first_name: "Jackie", last_name: "Bavaro" },
  { first_name: "Rajeev", last_name: "Behera" },
  { first_name: "Michael", last_name: "Belkin" },
  { first_name: "Sandeep", last_name: "Bhadra" },
  { first_name: "Dave", last_name: "Bogaty" },
  { first_name: "Zach", last_name: "Brock" },
  { first_name: "Steve", last_name: "Cary" },
  { first_name: "Yatin", last_name: "Chawathe" },
  { first_name: "Alex", last_name: "Chen" },
  { first_name: "Nick", last_name: "Cheng" },
  { first_name: "Maggie", last_name: "Cheng" },
  { first_name: "Allison", last_name: "Cheng" },
  { first_name: "Zach", last_name: "Cheng" },
  { first_name: "Frank", last_name: "Cheng" },
  { first_name: "Ben", last_name: "Cheng" },
  { first_name: "Lesley", last_name: "Cicciarella" },
  { first_name: "Adam", last_name: "Cicciarella" },
  { first_name: "Susan", last_name: "Colucci" },
  { first_name: "Dave", last_name: "Colucci" },
  { first_name: "Scott", last_name: "Conlon" },
  { first_name: "Emma", last_name: "Conlon" },
  { first_name: "Patrick", last_name: "Conlon" },
  { first_name: "Tom", last_name: "Danner" },
  { first_name: "Pamela", last_name: "Davis" },
  { first_name: "Meghan", last_name: "Day" },
  { first_name: "Jim", last_name: "Deng" },
  { first_name: "Jay", last_name: "DeYoung" },
  { first_name: "Kevin", last_name: "Duong" },
  { first_name: "Sarah", last_name: "Emerson" },
  { first_name: "Alexa", last_name: "Fairchild" },
  { first_name: "Ben", last_name: "Fishler" },
  { first_name: "Amina", last_name: "Ghrissi" },
  { first_name: "Stephen", last_name: "Goddard" },
  { first_name: "Mike", last_name: "Goldin" },
  { first_name: "Mike", last_name: "Goncalves" },
  { first_name: "Ed", last_name: "Goodman" },
  { first_name: "Jay", last_name: "Goodman" },
  { first_name: "Rishi", last_name: "Goyal" },
  { first_name: "Steve", last_name: "Granitz" },
  { first_name: "Derek", last_name: "Hadley" },
  { first_name: "Nancy", last_name: "Hadley" },
  { first_name: "Joe", last_name: "Handel" },
  { first_name: "Nat", last_name: "Harward" },
  { first_name: "Ben", last_name: "Heller" },
  { first_name: "Paul", last_name: "Hendricks" },
  { first_name: "Eric", last_name: "Hoppe" },
  { first_name: "Sarah", last_name: "Hoppe" },
  { first_name: "Ben", last_name: "Howard" },
  { first_name: "Josh", last_name: "Howarth" },
  { first_name: "Brad", last_name: "Hughes" },
  { first_name: "Lindsay", last_name: "Hughes" },
  { first_name: "Adam", last_name: "Hutz" },
  { first_name: "Vivian", last_name: "Jan" },
  { first_name: "Shreyas", last_name: "Kapur" },
  { first_name: "Patrick", last_name: "Karsh" },
  { first_name: "Caitlin", last_name: "Kennedy" },
  { first_name: "Kathryn", last_name: "Kennedy" },
  { first_name: "Jesse", last_name: "Knobel" },
  { first_name: "Melissa", last_name: "Knobel" },
  { first_name: "Elizabeth", last_name: "Kuczynski" },
  { first_name: "Hanna", last_name: "Kurniawati" },
  { first_name: "Matthew", last_name: "Landau" },
  { first_name: "Greg", last_name: "Laughlin" },
  { first_name: "Katie", last_name: "Laughlin" },
  { first_name: "Jack", last_name: "Levis" },
  { first_name: "Tamar", last_name: "Levis" },
  { first_name: "Nick", last_name: "Ligertwood" },
  { first_name: "Joanie", last_name: "Ligertwood" },
  { first_name: "Jeff", last_name: "Lin" },
  { first_name: "Kelly", last_name: "Liu" },
  { first_name: "Peter", last_name: "Loewen" },
  { first_name: "Liz", last_name: "Loewen" },
  { first_name: "Daniel", last_name: "Lu" },
  { first_name: "Alex", last_name: "Madry" },
  { first_name: "Jonah", last_name: "Marcus" },
  { first_name: "Roya", last_name: "Marcus" },
  { first_name: "Tyler", last_name: "McBrien" },
  { first_name: "Sean", last_name: "McBride" },
  { first_name: "Luke", last_name: "McGrath" },
  { first_name: "Sam", last_name: "Medina" },
  { first_name: "Paul", last_name: "Menchik" },
  { first_name: "Alison", last_name: "Menchik" },
  { first_name: "Derek", last_name: "Miller" },
  { first_name: "Josh", last_name: "Mordkoff" },
  { first_name: "Ryan", last_name: "Murdock" },
  { first_name: "Nicole", last_name: "Murdock" },
  { first_name: "Brendan", last_name: "Murphy" },
  { first_name: "Olivia", last_name: "Murphy" },
  { first_name: "Jen", last_name: "Ngai" },
  { first_name: "Jake", last_name: "Nie" },
  { first_name: "Tim", last_name: "O'Toole" },
  { first_name: "Brian", last_name: "Pacifico" },
  { first_name: "JP", last_name: "Parrish" },
  { first_name: "Sid", last_name: "Pattani" },
  { first_name: "Rachel", last_name: "Peckham" },
  { first_name: "Kait", last_name: "Poon" },
  { first_name: "David", last_name: "Price" },
  { first_name: "Lila", last_name: "Rabinovich" },
  { first_name: "Hunter", last_name: "Rae" },
  { first_name: "Arjun", last_name: "Ramachandran" },
  { first_name: "Justin", last_name: "Rao" },
  { first_name: "Talia", last_name: "Rao" },
  { first_name: "Charlotte", last_name: "Read" },
  { first_name: "Mike", last_name: "Read" },
  { first_name: "Phil", last_name: "Reinhart" },
  { first_name: "Carolyn", last_name: "Reinhart" },
  { first_name: "Brian", last_name: "Rowan" },
  { first_name: "Nat", last_name: "Scherzer" },
  { first_name: "Keith", last_name: "Schiller" },
  { first_name: "Randy", last_name: "Schofield" },
  { first_name: "Shivani", last_name: "Sharma" },
  { first_name: "Joe", last_name: "Shirk" },
  { first_name: "Stephanie", last_name: "Sica" },
  { first_name: "Ryan", last_name: "Smith" },
  { first_name: "Victoria", last_name: "Smith-Campbell" },
  { first_name: "Brad", last_name: "Soergel" },
  { first_name: "Liz", last_name: "Soergel" },
  { first_name: "Michael", last_name: "Solomon" },
  { first_name: "Jeff", last_name: "Spangenberg" },
  { first_name: "Sarah", last_name: "Spangenberg" },
  { first_name: "Mark", last_name: "Steinberg" },
  { first_name: "Dan", last_name: "Stevens" },
  { first_name: "Kyle", last_name: "Thompson" },
  { first_name: "Emily", last_name: "Thompson" },
  { first_name: "Phil", last_name: "Tseng" },
  { first_name: "Eliza", last_name: "Van Steen" },
  { first_name: "Abhinav", last_name: "Venkataraman" },
  { first_name: "Alisha", last_name: "Venkataraman" },
  { first_name: "Russ", last_name: "Vickery" },
  { first_name: "Alison", last_name: "Vickery" },
  { first_name: "Alex", last_name: "Wang" },
  { first_name: "Jade", last_name: "Watanabe" },
  { first_name: "Austin", last_name: "Werner" },
  { first_name: "Grant", last_name: "Widmer" },
  { first_name: "Becca", last_name: "Winer" },
  { first_name: "Mike", last_name: "Wittry" },
  { first_name: "Jon", last_name: "Wong" },
  { first_name: "TJ", last_name: "Wood" },
  { first_name: "Adam", last_name: "Wu" },
  { first_name: "Wenbo", last_name: "Wu" },
  { first_name: "Stephen", last_name: "Xie" },
  { first_name: "Chenyang", last_name: "Yuan" },
  { first_name: "Iris", last_name: "Yuan" },
  { first_name: "Olivia", last_name: "Zhang" },
  { first_name: "Max", last_name: "Zubkoff" },
  { first_name: "Thalia", last_name: "Zubkoff" },
];

export default function ConfirmedAttendees() {
  
  return (
    <div className="grid grid-cols-3 gap-x-3 gap-y-2 md:gap-x-4 md:gap-y-3 max-w-[700px] mx-auto">
      {attendees.map((guest, index) => (
        <div 
          key={index} 
          className="text-[#C2C2C2] text-xs md:text-sm font-bicyclette text-center uppercase"
        >
          {guest.first_name} {guest.last_name}
        </div>
      ))}
    </div>
  );
}
