
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpbbzmpqacbgqnyrnufb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwYmJ6bXBxYWNiZ3FueXJudWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNDY5MjcsImV4cCI6MjA2MTYyMjkyN30.0vBgGzVlb0XDJlhBthFqxYQp86MyK9LuOww137SxxCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
